export const errors = {
    en: {
        "invalidAddress": "Not a valid address",
        "adminWithSameEmail": "Admin with {{email}} Id already exist.",
        "noSuchAccount": "No such account exist with this email.",
        "WrongPassword": "Wrong Password Please fill Correct Password.",
        "invalidPickupAddress": "Not a valid pickup address.",
        "invalidDeliveryAddress": "Not a valid delivery address.",
        "accountAlreadyExist": "Account with given Phone number and Role already exist.",
        "noSuchAccountExist": "No such account exist.",
        "invalidMongoId": "{{key}} must be a valid mongo ID",
        "noDatafound": "No Record Found",
        "modelFound": "With this Name Model already exist",
        "alreadyExist": "Already Exists",
        "userExist": "User already Exist",
        "reasonExist": "Reason already Exist",
        "phoneNumberTaken": "Phone number already taken by some other user.",
        "invalidAction": "Invalid action",
        "unprocessableEntity": "Unprocessable entity",
        "somethingwrong": "Something went wrong",
        "bookingStatusError": "Status can't be changed from '{{old}}' state to '{{new}}' state.",
        "accountBlocked": "Account blocked by admin.",
        "sessionExpired": "Session expired! Please login again.",
        "noToken": "Invalid token",
        "unAuthRole": "Unauthorized role! Access denied",
        "incorrectOldPass": "Please enter correct old password",
        "accountUnverifiedAdmin": "Your Account is unverified, please contact Admin",
        "categoryWithSameName": "Category with {{catName}} Name already exist.",
        "exploreWithSameName": "Explore with {{exploreName}} Name already exist.",
        "categoryIdRequired": "CategoryId required",
        "exploreIdRequired": 'ExploreId required',
        "isActiveRequired": "IsActive key Required"
    },
    mace: {
        "invalidAddress": "Not a valid address",
        "adminWithSameEmail": "Admin with same Email already exist.",
        "noSuchAccount": "No such account exist with this email.",
        "WrongPassword": "Wrong Password Please fill Correct Password.",
        "invalidPickupAddress": "Not a valid pickup address.",
        "invalidDeliveryAddress": "Not a valid delivery address.",
        "accountAlreadyExist": "Account with given Phone number and Role already exist.",
        "noSuchAccountExist": "No such account exist.",
        "reasonExist": "Reason already Exist",
        "invalidMongoId": "{{key}} must be a valid mongo ID",
        "noDatafound": "No Record Found",
        "modelFoundmessage": "With this Name Model already exist",
        "alreadyExist": "Already Exists",
        "userExist": "Корисникот веќе излегува",
        "phoneNumberTaken": "Phone number already taken by some other user.",
        "invalidAction": "Invalid action",
        "unprocessableEntity": "Unprocessable entity",
        "somethingwrong": "Something went wrong",
        "bookingStatusError": "Status can't be changed from '{{old}}' state to '{{new}}' state.",
        "accountBlocked": "Account blocked by admin.",
        "sessionExpired": "Session expired! Please login again.",
        "noToken": "Invalid token",
        "unAuthRole": "Unauthorized role! Access denied",
        "incorrectOldPass": "Please enter correct old password",
        "accountUnverifiedAdmin": "Your Account is unverified, please contact Admin",
        "categoryWithSameName": "Category with {{catName}} Name already exist.",
        "exploreWithSameName": "Explore with {{exploreName}} Name already exist.",
        "categoryIdRequired": "CategoryId required",
        "exploreIdRequired": 'ExploreId required',
        "isActiveRequired": "IsActive key Required"

    }
}



export const success = {
    en: {
        "signupSuccessful": "Signup sucessfully",
        "loginSuccessful": "Login sucessfully",
        "accountExists": "Account already exist",
        "noSuchAccountExist": "No such account exist",
        "kycDone": "KYC Has been done sucessfully",
        "kycDetails": "KYC details fetched sucessfully",
        "gotUserProfile": "Got user profile sucessfully",
        "recordFetched": "Record fetched sucessfully",
        "updateSuccessful": "Update profile sucessfully",
        "respondSuccess": "You have responded successfully",
        "RecordFound": "Record found",
        "categoryAdded": "Category added sucessfully",
        "exploreAdded": "Explore added sucessfully",
        "deleteVendor": "Delete vehicle sucessfully",
        "vendorGot": "Got Vehicle sucessfully",
        "updateVendor": "Update vehicle sucessfully",
        "bookingUpdated": "Booking status changed successfully",
        "addressRemoved": "Address Removed",
        "issueReported": "issue Reported Successfully",
        "bookingGenerated": "booking Generated Successfully",
        "logOutSuccessful": "User logOut successfully",
        "userComment": "User Comments successfully",
        "updateSuccefully": "Update Successfully",
        "addRestaurant": "Restaurant added successfully",
        "doc_upload": "Documents uploaded successfully",
        "updateStatus": "Status updated successfully",
        "success": "success"
    },
    mace: {
        "signupSuccessful": "Signup sucessfully",
        "loginSuccessful": "Login sucessfully",
        "accountExists": "Account already exist",
        "noSuchAccountExist": "No such account exist",
        "kycDone": "KYC Has been done sucessfully",
        "kycDetails": "KYC details fetched sucessfully",
        "gotUserProfile": "Got user profile sucessfully",
        "recordFetched": "Record fetched sucessfully",
        "updateSuccessful": "Update profile sucessfully",
        "respondSuccess": "You have responded successfully",
        "RecordFound": "Record found",
        "categoryAdded": "Category added sucessfully",
        "exploreAdded": "Explore added sucessfully",
        "deleteVendor": "Delete vehicle sucessfully",
        "vendorGot": "Got Vehicle sucessfully",
        "updateVendor": "Update vehicle sucessfully",
        "bookingUpdated": "Booking status changed successfully",
        "addressRemoved": "Address Removed",
        "issueReported": "issue Reported Successfully",
        "bookingGenerated": "booking Generated Successfully",
        "logOutSuccessful": "User logOut successfully",
        "userComment": "User Comments successfully",
        "updateSuccefully": "Update Successfully",
        "addRestaurant": "Restaurant added successfully",
        "doc_upload": "Documents uploaded successfully",
        "updateStatus": "Status updated successfully",
        "success": "success"
    }
}

export const topics = {
    "All Customers": 'All_Customers',
    "All Business Owners": 'All_Business_Owners',
    "All Delivery Persons": 'All_Delivery_Persons',
    "All Customers & Business Owners": 'All_Customers_Business_Owners',
    "All Customers & Delivery Persons": 'All_Customers_Delivery_Persons',
    "All Delivery Persons & Business Owners": 'All_Delivery_Persons_Business_Owners',
    'All': 'All_Customers_Business_Owners_Delivery_Persons'
}


